from abc import ABC, abstractmethod
from typing import Optional
from .entities import Community, Membership, CommunityPost


class CommunityRepository(ABC):
    @abstractmethod
    def save(self, c: Community) -> Community: ...
    @abstractmethod
    def find_by_id(self, cid: str) -> Optional[Community]: ...
    @abstractmethod
    def find_by_slug(self, slug: str) -> Optional[Community]: ...
    @abstractmethod
    def search(self, q: str, limit: int, offset: int) -> list[Community]: ...
    @abstractmethod
    def list_all(self, limit: int, offset: int) -> list[Community]: ...
    @abstractmethod
    def update(self, c: Community) -> Community: ...
    @abstractmethod
    def increment_member_count(self, cid: str, delta: int) -> None: ...
    @abstractmethod
    def delete(self, cid: str) -> bool: ...


class MembershipRepository(ABC):
    @abstractmethod
    def save(self, m: Membership) -> Membership: ...
    @abstractmethod
    def find(self, cid: str, uid: str) -> Optional[Membership]: ...
    @abstractmethod
    def delete(self, cid: str, uid: str) -> bool: ...
    @abstractmethod
    def get_members(self, cid: str, limit: int, offset: int) -> list[Membership]: ...
    @abstractmethod
    def get_user_communities(self, uid: str) -> list[str]: ...
    @abstractmethod
    def update_role(self, cid: str, uid: str, role: str) -> bool: ...


class CommunityPostRepository(ABC):
    @abstractmethod
    def save(self, p: CommunityPost) -> CommunityPost: ...
    @abstractmethod
    def find_by_id(self, pid: str) -> Optional[CommunityPost]: ...
    @abstractmethod
    def find_by_community(self, cid: str, limit: int, offset: int) -> list[CommunityPost]: ...
    @abstractmethod
    def soft_delete(self, pid: str) -> bool: ...
    @abstractmethod
    def pin(self, pid: str, pinned: bool) -> bool: ...


class EventPublisher(ABC):
    @abstractmethod
    def publish(self, event_type: str, topic: str, key: str, payload: dict) -> None: ...
